export interface IgetList {
    asUserId : string,
    asAcademicYearId : string,
    asUserRoleId: string,
    asSchoolId: string,
    asFilter : string,
    asPageIndex : number,
    asMonthId : string,
    abIsSMSCenter: string
}

export interface GetMessagesResult{
    GetMessagesResult:[{
        Attachments:{},
        DetailsId:string,
        ReceiverDetailsId:string,
        DisplayText: string,
        Subject:string,
        IsAttachment:string,
        Attachment:string,
        Body:string,
        UserName:string,
        Date:String,
        Time:string,
        RecieverName:string,
        IsDeletedFromUser:string,
        SenderUserId:string,
        SenderUserRoleId:string,
        IsDeleted:boolean,
        AcademicYearId:string,
        InsertedById:string,
        IsRead:string,
        IsNew:string,
        ReceiverUserRoleId:string,
        ReceiverUserId:string,
        SchoolId:string,
        SenderName:string,
        LoggedInUserNameForMessage:string,
        AttachmentDisplayName:string,
        MESSAGECOUNT:number,
        IsBdayApplicable:string,
        DateOfBirth:string,
        IsLockedUser: Boolean,
        Id:number,
        PageLabel:string
    }]
}
export interface GetScheduledSMSResult{
    GetScheduledSMSResult:[{
        Attachments:{},
        DetailsId:string,
        ReceiverDetailsId:string,
        DisplayText: string,
        Subject:string,
        IsAttachment:string,
        Attachment:string,
        Body:string,
        UserName:string,
        Date:String,
        Time:string,
        RecieverName:string,
        IsDeletedFromUser:string,
        SenderUserId:string,
        SenderUserRoleId:string,
        IsDeleted:boolean,
        AcademicYearId:string,
        InsertedById:string,
        IsRead:string,
        IsNew:string,
        ReceiverUserRoleId:string,
        ReceiverUserId:string,
        SchoolId:string,
        SenderName:string,
        LoggedInUserNameForMessage:string,
        AttachmentDisplayName:string,
        MESSAGECOUNT:number,
        IsBdayApplicable:string,
        DateOfBirth:string,
        IsLockedUser: Boolean,
        Id:number,
        PageLabel:string
    }]
}
